from src.logging import logging
logging.info("Importing chatterbox.py...")
import src.tts_types.base_tts as base_tts
imported = False
try:
    logging.info("Trying to import chatterbox")
    from libraries.chatterbox.tts import ChatterboxTTS
    # from libraries.chatterbox.vc import ChatterboxVC
    import random
    # import numpy as np
    # import torch
    import torchaudio as ta
    # import os
    import io
    imported = True
    logging.info("Imported chatterbox")
except Exception as e:
    logging.error(f"Failed to import torch and torchaudio: {e}")
    raise e
logging.info("Imported required libraries in chatterbox.py")

tts_slug = "chatterbox"
default_settings = {
    "chatterbox_device": "cuda",
    "chatterbox_default_temperature": 0.5,
    "chatterbox_default_exaggeration": 0.5,
    "chatterbox_default_cfgw": 0.8,
    "chatterbox_max_tokens": 1024,
    "chatterbox_watermark": False,
    "chatterbox_batch_size": 300,
    "chatterbox_batch_type": "paragraph", # paragraph, sentence, word
    "chatterbox_volume": 1.0,
    "chatterbox_banned_voice_models": [],
}
settings_description = {
    "chatterbox_device": "The device to run the Chatterbox model on. This can be changed in config.json. The default is 'cuda', but if you have a compatible NVIDIA GPU, you can set this to 'cuda' to significantly speed up synthesis times. If you don't have a compatible GPU, you can set this to 'cpu', but keep in mind that synthesis times will be significantly longer.",
    "chatterbox_default_temperature": "Temperature of the voice, higher values make the voice sound more random and less predictable. Can make voices less robotic and more human-like, but can also make them sound more unnatural and have glitches/artifacts.",
    "chatterbox_default_exaggeration": "The default settings (0.5) work well for most prompts. Higher exaggeration tends to speed up speech, reducing cfg_weight helps compensate with slower, more deliberate pacing.",
    "chatterbox_default_cfgw": "If the reference speaker has a fast speaking style, lowering cfg_weight to around 0.3 can improve pacing.",
    "chatterbox_max_tokens": "The maximum number of tokens to use for synthesis. Higher values can improve the quality of longer sentences, but can also increase synthesis times and memory usage.",
    "chatterbox_watermark": "Whether to add a watermark to the generated audio. This can be used to identify audio generated by Chatterbox, but it can also add a subtle noise to the audio.",
    "chatterbox_batch_size": "The batch size to use for synthesis. Higher values can speed up synthesis times, but can also increase memory usage. The optimal batch size can vary depending on the length of the input text and the available hardware.",
    "chatterbox_batch_type": "The type of batching to use for synthesis. 'paragraph' batches by paragraph, 'sentence' batches by sentence, and 'word' batches by word. Batching by paragraph can be faster for longer inputs, but can also lead to less coherent speech. Batching by sentence can be a good middle ground, while batching by word can produce the most coherent speech but can also be the slowest.",
    "chatterbox_volume": "The volume of the generated audio. This can be used to increase or decrease the volume of the generated audio. The default is 1.0, which means no change in volume. Values greater than 1.0 will increase the volume, while values less than 1.0 will decrease the volume.",
    "chatterbox_banned_voice_models": "A list of voice models to ban from being used by Chatterbox. This can be changed in config.json. This is useful if you have a voice model that causes issues with Chatterbox, such as extremely long synthesis times or crashes."
}
options = {}
settings = {}
loaded = False
description = "is a \"production-grade open source TTS model. Licensed under MIT, Chatterbox has been benchmarked against leading closed-source systems like ElevenLabs, and is consistently preferred in side-by-side evaluations.\" Very good emotional tinting in speaking, can do a lot of different voices very well, and isn't unusably slow, though it is a bit slower than xTTS 2 on the same hardware. It needs 6GB of VRAM to run on GPU, but it can run on CPU as well, albiet, very slowly, about five times slower than the GPU(2080 ti) on a Ryzen 9 5950X with DDR4."
class Synthesizer(base_tts.base_Synthesizer):
    def __init__(self, conversation_manager, ttses = []):
        global tts_slug, default_settings, loaded
        super().__init__(conversation_manager)
        self.tts_slug = tts_slug
        self._default_settings = default_settings
        logging.info(f"Initializing {self.tts_slug}...")

        self.model = None  # Initialize model as None
        self.model_type = "tts"  # Default model type
        self.get_or_load_tts_model() # Load TTS model on startup

        logging.info(f'{self.tts_slug} speaker wavs folders: {self.speaker_wavs_folders}')
        logging.config(f'{self.tts_slug} - Available voices: {self.voices()}')
        if len(self.voices()) > 0:
            random_voice = random.choice(self.voices())
            self._say("Chatterbox is ready to go.", random_voice)
        loaded = True

    def get_or_load_tts_model(self):
        """Loads the ChatterboxTTS model if it hasn't been loaded already,
        and ensures it's on the correct device."""
        if self.model is None or self.model_type != "tts":
            self.model_type = "tts"
            # print("TTS Model not loaded, initializing...")
            logging.info(f'{self.tts_slug} - TTS Model not loaded, initializing...')
            try:
                self.model = ChatterboxTTS.from_pretrained(self.config.chatterbox_device)
                if hasattr(self.model, 'to') and str(self.model.device) != self.config.chatterbox_device:
                    self.model.to(self.config.chatterbox_device)
                # print(f"Model loaded successfully. Internal device: {getattr(self.model, 'device', 'N/A')}")
                logging.info(f'{self.tts_slug} - Model loaded successfully. Internal device: {getattr(self.model, "device", "N/A")}')
            except Exception as e:
                # print(f"Error loading model: {e}")
                logging.error(f'{self.tts_slug} - Error loading model: {e}')
                raise
            
    # def get_or_load_vc_model(self):
    #     if self.model is None or self.model_type != "vc":
    #         self.model_type = "vc"
    #         # print("VC Model not loaded, initializing...")
    #         logging.info(f'{self.tts_slug} - VC Model not loaded, initializing...')
    #         try:
    #             self.model = ChatterboxVC.from_pretrained(self.config.chatterbox_device)
    #             if hasattr(self.model, 'to') and str(self.model.device) != self.config.chatterbox_device:
    #                 self.model.to(self.config.chatterbox_device)
    #             # print(f"Model loaded successfully. Internal device: {getattr(self.model, 'device', 'N/A')}")
    #             logging.info(f'{self.tts_slug} - Model loaded successfully. Internal device: {getattr(self.model, "device", "N/A")}')
    #         except Exception as e:
    #             # print(f"Error loading model: {e}")
    #             logging.error(f'{self.tts_slug} - Error loading model: {e}')
    #             raise

    def voices(self):
        """Return a list of available voices"""
        voices = super().voices()
        for banned_voice in self.config.chatterbox_banned_voice_models:
            if banned_voice in voices:
                voices.remove(banned_voice)
        return voices
    
    @property
    def default_voice_model_settings(self):
        return {
            "exaggeration": self.config.chatterbox_default_exaggeration,
            "temperature": self.config.chatterbox_default_temperature,
            "cfgw": self.config.chatterbox_default_cfgw,
        }
    
    def _synthesize(self, voiceline, voice_model, voiceline_location, settings, aggro=0):
        """Synthesize the audio for the character specified using ParlerTTS"""
        logging.output(f'{self.tts_slug} - synthesizing {voiceline} with voice model "{voice_model}"...')
        speaker_wav_path = self.get_speaker_wav_path(voice_model)
        logging.output(f'{self.tts_slug} - using voice model settings: {settings}')
        if not voiceline.endswith(".") and not voiceline.endswith("!") and not voiceline.endswith("?"): # Add a period to the end of the voiceline if it doesn't have one. StyleTTS2 will make a strange blip sound if the voiceline doesn't end with a period.
            voiceline += "."
        
        if self.model is None:
            raise RuntimeError("TTS model is not loaded.")

        wav = self.model.generate(
            voiceline,
            batch_size=self.config.chatterbox_batch_size,
            batch_type=self.config.chatterbox_batch_type.lower(),
            audio_prompt_path=speaker_wav_path,
            exaggeration=settings.get("exaggeration", default_settings["chatterbox_default_exaggeration"]),
            temperature=settings.get("temperature", default_settings["chatterbox_default_temperature"]),
            cfg_weight=settings.get("cfgw", default_settings["chatterbox_default_cfgw"]),
            max_tokens=self.config.chatterbox_max_tokens,  # Limit to 300 characters
            watermark=self.config.chatterbox_watermark,
        )         
        # Save the wav file
        bytes_io_file = io.BytesIO()
        wav = wav * self.config.chatterbox_volume
        # ta.save(voiceline_location, wav, self.model.sr)
        ta.save(bytes_io_file, wav, self.model.sr, format='wav')
        bytes_io_file.seek(0)
        self.convert_to_16bit(bytes_io_file,voiceline_location, self.model.sr)
        logging.output(f'{self.tts_slug} - synthesized {voiceline} with voice model "{voice_model}"')